# Manual: https://github.com/artgris/FileManagerBundle
############################################################
artgris_file_manager:
    conf:
        default:
            dir: "../../public/file_manager/uploads"
