# Manual: https://github.com/artgris/FileManagerBundle
############################################################
artgris_file_manager:
    conf:
        default:
            dir: "../../public/shared_media/artgris/filemanager"
