doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'

        logging: true
        driver: 'pdo_mysql'
        server_version: '10.11.19-MariaDB'
        charset: utf8
        
        default_table_options:
            charset: utf8
            collate: utf8_unicode_ci
        
        mapping_types:
            enum: string
        
        types:
            set: Vankosoft\ApplicationBundle\Doctrine\DBAL\Types\SetType
        
    orm:
        auto_mapping: true
        validate_xml_mapping: true
        
        naming_strategy: doctrine.orm.naming_strategy.underscore
        
        mappings:
            App:
                is_bundle: false
                type: attribute
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App

            gedmo_tree:
                type: attribute
                prefix: Gedmo\Tree\Entity
                dir: "%kernel.project_dir%/vendor/gedmo/doctrine-extensions/src/Tree/Entity"
                alias: GedmoTree # (optional) it will default to the name set for the mapping
                is_bundle: false
                
            translatable:
                type: attribute
                prefix: Gedmo\Translatable\Entity
                dir: "%kernel.project_dir%/vendor/gedmo/doctrine-extensions/src/Translatable/Entity/MappedSuperclass"
                alias: GedmoTranslatable
                is_bundle: false
                
            loggable:
                type: attribute
                prefix: Gedmo\Loggable\Entity
                dir: "%kernel.project_dir%/vendor/gedmo/doctrine-extensions/src/Loggable/Entity/MappedSuperclass"
                alias: GedmoLoggable
                is_bundle: false
                
            sortable:
                type: attribute
                prefix: Gedmo\Sortable\Entity
                dir: "%kernel.project_dir%/vendor/gedmo/doctrine-extensions/src/Sortable/Entity"
                alias: GedmoSortable
                is_bundle: false

        filters:
            softdeleteable:
                class: Gedmo\SoftDeleteable\Filter\SoftDeleteableFilter
                enabled: false # Enable it if you need Soft Deleteable Extension to not show Deleted Records
