doctrine_migrations:
    enable_profiler: '%kernel.debug%'
    
    migrations_paths:
        'App\DoctrineMigrations': '%kernel.project_dir%/src/DoctrineMigrations'

    storage:
        table_storage:
            table_name: 'VSAPP_Migrations'
            version_column_name: 'version'
            version_column_length: 1024
            executed_at_column_name: 'executed_at'

    services:
        'Doctrine\Migrations\Version\MigrationFactory': 'SyliusLabs\DoctrineMigrationsExtraBundle\Factory\ContainerAwareVersionFactory'
        'Doctrine\Migrations\Version\Comparator': 'SyliusLabs\DoctrineMigrationsExtraBundle\Comparator\TopologicalVersionComparator'

