knp_gaufrette:
    adapters:
        vs_application_image:
            local:
                #directory: %kernel.cache_dir%/../media/image
                directory: "%kernel.project_dir%/public/admin-panel/media/image"
                create: true
    filesystems:
        vs_application_image:
            adapter: "%vs_cms.uploader.filesystem%"
