oneup_flysystem:
    adapters:
        vs_application_app_pictures:
            local:
                location: "%vs_cms.filemanager_shared_media_gaufrette.app_pictures%"
        vs_application_profile:
            local:
                location: "%vs_cms.filemanager_shared_media_gaufrette.profile%"
        vs_application_filemanager:
            local:
                location: "%vs_cms.filemanager_shared_media_gaufrette.filemanager%"
        vs_application_slider:
            local:
                location: "%vs_cms.filemanager_shared_media_gaufrette.slider%"
        vs_application_kanbanboard_task_attachments:
            ftp:
                options:
                    host: '%env(VANKOSOFT_API_FTP_HOST)%'
                    root: '%env(VANKOSOFT_API_FTP_ROOT)%'
                    username: '%env(VANKOSOFT_API_FTP_USER)%'
                    password: '%env(VANKOSOFT_API_FTP_PASS)%'
                    ignorePassiveAddress: false
                    passive: true
    
    filesystems:
        vs_application_app_pictures:
            adapter: "%vs_cms.gaufrette.app_pictures.filesystem%"
        vs_application_profile:
            adapter: "%vs_cms.gaufrette.profile.filesystem%"
        vs_application_filemanager:
            adapter: "%vs_cms.gaufrette.filemanager.filesystem%"
        vs_application_slider:
            adapter: "%vs_cms.gaufrette.slider.filesystem%"
        vs_application_kanbanboard_task_attachments:
            adapter: vs_application_kanbanboard_task_attachments
