sylius_theme:
    sources:
        filesystem:
            directories:
                - "%kernel.project_dir%/vendor/vankosoft/application-themes/AdminPanel_VelzonDefault"
                - "%kernel.project_dir%/themes"