vs_cms:
    resources:
        pages:
            classes:
                model: App\Entity\Cms\Page
        page_categories:
            classes:
                model: App\Entity\Cms\PageCategory
        multipage_toc:
            classes:
                model: App\Entity\Cms\MultiPageToc
        multipage_toc_page:
            classes:
                model: App\Entity\Cms\TocPage
        file_manager:
            classes:
                model: App\Entity\Cms\FileManager
        file_manager_file:
            classes:
                model: App\Entity\Cms\FileManagerFile
