# See dos how to configure the bundle: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
    # valid drivers options include "gd" or "gmagick" or "imagick"
    driver: "gd"
    
    loaders:
        default:
            filesystem:
                data_root: "%kernel.project_dir%/"
    
    resolvers:
        default:
            web_path: ~

    filter_sets:
        cache: ~
        
        profile_form_thumb:
            quality: 75
            filters:
                thumbnail: { size: [120, 90], mode: outbound }
                background: { size: [124, 94], position: center, color: '#000000' }
