vs_cms_pages:
    resource: "@VSCmsBundle/Resources/config/routing/pages.yml"
    prefix: /
    
vs_cms_images:
    resource: "@VSCmsBundle/Resources/config/routing/images.yml"
    prefix: /

vs_cms_toc:
    resource: "@VSCmsBundle/Resources/config/routing/toc.yml"
    prefix: /

vs_cms_filemanager:
    resource: "@VSCmsBundle/Resources/config/routing/filemanager.yml"
    prefix: /vs_filemanager
