imports:
    - { resource: services/menu.yaml }

# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    lang: 'en'
    locale: 'en_US'
    languages:
        en: English
        bg: Български
    applicationTitle: 'SuperAdmin Panel'
    
    vs_application.version: !php/const App\AdminPanelKernel::VERSION
    vs_application.public_dir: "%kernel.project_dir%/public/admin-panel"
    vs_application.page_categories.taxonomy_code: 'page-categories'
    
    vs_users.login_route: 'vs_application_login'
    vs_users.login_by: 'username'
    
    # The cookie_lifetime would be set to a relatively high value, 
    # and the garbage collection gc_maxlifetime would be set to destroy sessions at whatever the desired idle period is.
    #########################################################################################################################
    vs_users.cookie_lifetime: 86400 # 24 hours
    vs_users.gc_maxlifetime: 1800   # 30 minutes
    vs_users.api_token.lifetime: 3600
    
    vs_user.profile_pictures_dir: '%kernel.project_dir%/var/uploads/profile_pictures'
    vs_cms.image_uploader.filesystem: vs_application_image
    vs_cms.filemanager_uploader.filesystem: vs_application_filemanager

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../../src/*'
        exclude:
            - '../../src/DependencyInjection/'
            - '../../src/Entity/'
            - '../../src/Form/'
            - '../../src/AdminPanelKernel.php'
            - '../../src/Tests/'
            
    App\Controller\:
        resource: '../../src/Controller'
        tags: ['controller.service_arguments']
        autowire: true
            
    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

